### ISSUE TITLE
PID file not deleting

### ISSUE THREAD

**Issue by ppuorro** [madflojo/rsync-cron-wrapper#1]
Hi

At the completion of the job, the PID file isnt getting deleted. I ensured the crontab has the rights to delete a file in the directory and ensured the config file is correct. Anything you can suggest? This is a helpful tool for a project im doing and would love to get it working.

**Comment by madflojo** [comment]
Does the job finish or fail?

**Comment by ppuorro** [comment]
It looked to finish but next run failed because the PID was there.

**Comment by madflojo** [comment]
Let me know if 6848f30 fixes it or not, I suspect the issue is your `rynsc` isn't returning a successful exit code and as such the process dies leaving the pid file.
